### PR TITLE
Update submissions.csv

### PR DESCRIPTION
**Pull request by nosayuri**
Submitting my Grocery List exercise updated and complete.

### CODE REVIEW

**Comment by s2t2** [comment]
Hey @nosayuri it looks like you may have updated your fork before this PR was merged, which complicates things. I will merge your contributions separately.

Also, I took a look at your updated python datatypes exercise. When you get a chance, please rename the file in that repo from `grocery.py` to `groceries.py`. Thanks!

**Comment by s2t2** [comment]
Closed in favor of #93.

**Comment by nosayuri** [comment]
Hi Prof Rossetti, thank you for the notifying me and sorry about that...
Can I redo the merging before class and still have it considered within the
deadline?

**Comment by s2t2** [comment]
@nosayuri in general, yes. however I have done it for you this first time.

**Comment by s2t2** [comment]
You addressed one of the submissions with #93 and I addressed the other with 6e9a388

**Comment by nosayuri** [comment]
Thank you!

**Comment by nosayuri** [comment]
Hi Professor Rosetti,
I renamed the file to the correct name of groceries.py on the same link
that I used before: https://github.com/nosayuri/Grocery-List-Final
Do I need to merge or make the pull request again?

Thank you for your patience!
Noemi

**Pull request closed without merging**
